#!/bin/bash
# ClawHub Skill Discovery Session
# Multi-agent skill enhancement for Magi, Beeb, Marvin Jr.

cd /home/magi/clawd
mkdir -p logs

echo "🔍 ClawHub Skill Discovery Session Started - $(date)" | tee -a logs/skill-discovery.log

# Check if clawhub CLI is available
if ! command -v clawhub &> /dev/null; then
    echo "⚠️ ClawHub CLI not found. Installing..."
    npm install -g @clawhub/cli
fi

echo "📊 Searching for most downloaded skills..." | tee -a logs/skill-discovery.log
clawhub search --sort downloads --limit 20 > /tmp/clawhub-popular.txt 2>&1

echo "🤖 Searching for self-improving agent skills..." | tee -a logs/skill-discovery.log  
clawhub search "self-improving" --limit 10 > /tmp/clawhub-self-improving.txt 2>&1
clawhub search "agent enhancement" --limit 10 >> /tmp/clawhub-self-improving.txt 2>&1

echo "📧 Searching for email/communication skills for Beeb..." | tee -a logs/skill-discovery.log
clawhub search "email" --limit 10 > /tmp/clawhub-email.txt 2>&1
clawhub search "gmail" --limit 10 >> /tmp/clawhub-email.txt 2>&1
clawhub search "GOG" --limit 5 >> /tmp/clawhub-email.txt 2>&1

echo "🔧 Searching for automation and monitoring skills..." | tee -a logs/skill-discovery.log
clawhub search "automation" --limit 10 > /tmp/clawhub-automation.txt 2>&1
clawhub search "monitoring" --limit 10 >> /tmp/clawhub-automation.txt 2>&1

echo "🛡️ Preparing skill recommendations with security analysis..." | tee -a logs/skill-discovery.log

# Create comprehensive recommendation report
REPORT_FILE="~/clawd/skills-discovery-$(date +%Y%m%d-%H%M).md"

cat > "$REPORT_FILE" << 'REPORT_EOF'
# 🎯 ClawHub Skill Discovery Report

**Generated:** $(date)  
**Target Agents:** Magi (orchestrator), Beeb (ops-scout), Marvin Jr. (builder-ops)  
**Goal:** Enhance multi-agent capabilities with popular and specialized skills

## 📊 Most Popular Skills (Top Downloads)

$(head -20 /tmp/clawhub-popular.txt 2>/dev/null || echo "Search results unavailable")

## 🤖 Self-Improving Agent Skills

$(cat /tmp/clawhub-self-improving.txt 2>/dev/null || echo "Search results unavailable")

## 📧 Email/Communication Skills (Priority for Beeb)

$(cat /tmp/clawhub-email.txt 2>/dev/null || echo "Search results unavailable")

## 🔧 Automation & Monitoring Skills

$(head -15 /tmp/clawhub-automation.txt 2>/dev/null || echo "Search results unavailable")

## 🎯 Installation Recommendations

### High Priority Skills
1. **Self-improving agent skills** - For autonomous capability enhancement
2. **Email/Gmail skills** - For Beeb's communication and triage capabilities  
3. **Monitoring skills** - For system health and performance tracking
4. **Popular automation skills** - Based on community downloads

### Agent Assignments
- **Magi:** Self-improving, orchestration, and coordination skills
- **Beeb:** Email, social monitoring, and communication skills  
- **Marvin Jr.:** Automation, monitoring, and infrastructure skills

### Security Protocol
1. **Use skill-guard** for security validation before installing
2. **Manual review** of skill code for high-privilege skills
3. **Test individually** before deploying across all agents
4. **Document new capabilities** in TOOLS.md after installation

### Installation Commands
```bash
# Security scan first
~/clawd/skills/skill-guard/scripts/safe-install.sh <skill-name>

# Install after validation  
clawhub install <skill-name>

# Document new capabilities
echo "Added <skill-name> - <description>" >> TOOLS.md
```

## 📋 Next Steps

1. **Review this report** and select promising skills
2. **Run security scans** on selected skills using skill-guard
3. **Install and test** skills individually
4. **Deploy to appropriate agents** based on role assignments
5. **Update documentation** with new capabilities

---
*Report generated by automated ClawHub discovery session*
REPORT_EOF

echo "✅ ClawHub skill discovery complete!" | tee -a logs/skill-discovery.log
echo "📄 Report saved to: $REPORT_FILE" | tee -a logs/skill-discovery.log
echo "🔍 Check the report for recommended skills and installation instructions" | tee -a logs/skill-discovery.log

# Clean up temporary files
rm -f /tmp/clawhub-*.txt

echo "🚀 Skill discovery session completed successfully!" | tee -a logs/skill-discovery.log
